<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Tracer.proto

namespace Com\Thapovan\Orion\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.thapovan.orion.proto.BulkRequest</code>
 */
class BulkRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string auth_token = 1;</code>
     */
    private $auth_token = '';
    /**
     * Generated from protobuf field <code>repeated .com.thapovan.orion.proto.Span span_data = 2;</code>
     */
    private $span_data;

    public function __construct() {
        \GPBMetadata\Tracer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string auth_token = 1;</code>
     * @return string
     */
    public function getAuthToken()
    {
        return $this->auth_token;
    }

    /**
     * Generated from protobuf field <code>string auth_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->auth_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.thapovan.orion.proto.Span span_data = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpanData()
    {
        return $this->span_data;
    }

    /**
     * Generated from protobuf field <code>repeated .com.thapovan.orion.proto.Span span_data = 2;</code>
     * @param \Com\Thapovan\Orion\Proto\Span[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpanData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Com\Thapovan\Orion\Proto\Span::class);
        $this->span_data = $arr;

        return $this;
    }

}

