<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Tracer.proto

namespace Com\Thapovan\Orion\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.thapovan.orion.proto.ControlRequest</code>
 */
class ControlRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.ControlRequest.RequestType request_type = 1;</code>
     */
    private $request_type = 0;
    protected $params;

    public function __construct() {
        \GPBMetadata\Tracer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.ControlRequest.RequestType request_type = 1;</code>
     * @return int
     */
    public function getRequestType()
    {
        return $this->request_type;
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.ControlRequest.RequestType request_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRequestType($var)
    {
        GPBUtil::checkEnum($var, \Com\Thapovan\Orion\Proto\ControlRequest_RequestType::class);
        $this->request_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct protoStruct = 2;</code>
     * @return \Google\Protobuf\Struct
     */
    public function getProtoStruct()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct protoStruct = 2;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setProtoStruct($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jsonString = 3;</code>
     * @return string
     */
    public function getJsonString()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>string jsonString = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setJsonString($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getParams()
    {
        return $this->whichOneof("params");
    }

}

