<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Tracer.proto

namespace Com\Thapovan\Orion\Proto;

/**
 * Protobuf enum <code>Com\Thapovan\Orion\Proto\ControlRequest\RequestType</code>
 */
class ControlRequest_RequestType
{
    /**
     * Generated from protobuf enum <code>AUTH = 0;</code>
     */
    const AUTH = 0;
    /**
     * Generated from protobuf enum <code>END_STREAM = 1;</code>
     */
    const END_STREAM = 1;
}

