<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events.proto

namespace Com\Thapovan\Orion\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.thapovan.orion.proto.LogEvent</code>
 */
class LogEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 event_id = 1;</code>
     */
    private $event_id = 0;
    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.LogLevel level = 2;</code>
     */
    private $level = 0;
    /**
     * Generated from protobuf field <code>string message = 3;</code>
     */
    private $message = '';
    protected $metadata;

    public function __construct() {
        \GPBMetadata\Events::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 event_id = 1;</code>
     * @return int|string
     */
    public function getEventId()
    {
        return $this->event_id;
    }

    /**
     * Generated from protobuf field <code>int64 event_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkInt64($var);
        $this->event_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.LogLevel level = 2;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.LogLevel level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkEnum($var, \Com\Thapovan\Orion\Proto\LogLevel::class);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct protoStruct = 4;</code>
     * @return \Google\Protobuf\Struct
     */
    public function getProtoStruct()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct protoStruct = 4;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setProtoStruct($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jsonString = 5;</code>
     * @return string
     */
    public function getJsonString()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>string jsonString = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setJsonString($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMetadata()
    {
        return $this->whichOneof("metadata");
    }

}

