<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events.proto

namespace Com\Thapovan\Orion\Proto;

/**
 * Protobuf enum <code>Com\Thapovan\Orion\Proto\LogLevel</code>
 */
class LogLevel
{
    /**
     * Generated from protobuf enum <code>DEBUG = 0;</code>
     */
    const DEBUG = 0;
    /**
     * Generated from protobuf enum <code>INFO = 1;</code>
     */
    const INFO = 1;
    /**
     * Generated from protobuf enum <code>WARN = 2;</code>
     */
    const WARN = 2;
    /**
     * Generated from protobuf enum <code>ERROR = 3;</code>
     */
    const ERROR = 3;
    /**
     * Generated from protobuf enum <code>CRITICAL = 4;</code>
     */
    const CRITICAL = 4;
}

