<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Span.proto

namespace Com\Thapovan\Orion\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.thapovan.orion.proto.Span</code>
 */
class Span extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.Trace trace_context = 1;</code>
     */
    private $trace_context = null;
    /**
     * Generated from protobuf field <code>string span_id = 2;</code>
     */
    private $span_id = '';
    /**
     * Generated from protobuf field <code>uint64 timestamp = 6;</code>
     */
    private $timestamp = 0;
    /**
     * Generated from protobuf field <code>string service_name = 7;</code>
     */
    private $service_name = '';
    /**
     * Generated from protobuf field <code>string event_location = 8;</code>
     */
    private $event_location = '';
    /**
     * Generated from protobuf field <code>string parent_span_id = 9;</code>
     */
    private $parent_span_id = '';
    protected $event;

    public function __construct() {
        \GPBMetadata\Span::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.Trace trace_context = 1;</code>
     * @return \Com\Thapovan\Orion\Proto\Trace
     */
    public function getTraceContext()
    {
        return $this->trace_context;
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.Trace trace_context = 1;</code>
     * @param \Com\Thapovan\Orion\Proto\Trace $var
     * @return $this
     */
    public function setTraceContext($var)
    {
        GPBUtil::checkMessage($var, \Com\Thapovan\Orion\Proto\Trace::class);
        $this->trace_context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string span_id = 2;</code>
     * @return string
     */
    public function getSpanId()
    {
        return $this->span_id;
    }

    /**
     * Generated from protobuf field <code>string span_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSpanId($var)
    {
        GPBUtil::checkString($var, True);
        $this->span_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.StartEvent start_event = 3;</code>
     * @return \Com\Thapovan\Orion\Proto\StartEvent
     */
    public function getStartEvent()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.StartEvent start_event = 3;</code>
     * @param \Com\Thapovan\Orion\Proto\StartEvent $var
     * @return $this
     */
    public function setStartEvent($var)
    {
        GPBUtil::checkMessage($var, \Com\Thapovan\Orion\Proto\StartEvent::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.EndEvent end_event = 4;</code>
     * @return \Com\Thapovan\Orion\Proto\EndEvent
     */
    public function getEndEvent()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.EndEvent end_event = 4;</code>
     * @param \Com\Thapovan\Orion\Proto\EndEvent $var
     * @return $this
     */
    public function setEndEvent($var)
    {
        GPBUtil::checkMessage($var, \Com\Thapovan\Orion\Proto\EndEvent::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.LogEvent log_event = 5;</code>
     * @return \Com\Thapovan\Orion\Proto\LogEvent
     */
    public function getLogEvent()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.LogEvent log_event = 5;</code>
     * @param \Com\Thapovan\Orion\Proto\LogEvent $var
     * @return $this
     */
    public function setLogEvent($var)
    {
        GPBUtil::checkMessage($var, \Com\Thapovan\Orion\Proto\LogEvent::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 6;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service_name = 7;</code>
     * @return string
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * Generated from protobuf field <code>string service_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event_location = 8;</code>
     * @return string
     */
    public function getEventLocation()
    {
        return $this->event_location;
    }

    /**
     * Generated from protobuf field <code>string event_location = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEventLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->event_location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parent_span_id = 9;</code>
     * @return string
     */
    public function getParentSpanId()
    {
        return $this->parent_span_id;
    }

    /**
     * Generated from protobuf field <code>string parent_span_id = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setParentSpanId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_span_id = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getEvent()
    {
        return $this->whichOneof("event");
    }

}

