<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events.proto

namespace Com\Thapovan\Orion\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.thapovan.orion.proto.StartEvent</code>
 */
class StartEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 event_id = 1;</code>
     */
    private $event_id = 0;
    protected $metadata;

    public function __construct() {
        \GPBMetadata\Events::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 event_id = 1;</code>
     * @return int|string
     */
    public function getEventId()
    {
        return $this->event_id;
    }

    /**
     * Generated from protobuf field <code>int64 event_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkInt64($var);
        $this->event_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct protoStruct = 2;</code>
     * @return \Google\Protobuf\Struct
     */
    public function getProtoStruct()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct protoStruct = 2;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setProtoStruct($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jsonString = 3;</code>
     * @return string
     */
    public function getJsonString()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>string jsonString = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setJsonString($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMetadata()
    {
        return $this->whichOneof("metadata");
    }

}

