<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Tracer.proto

namespace Com\Thapovan\Orion\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.thapovan.orion.proto.StreamRequest</code>
 */
class StreamRequest extends \Google\Protobuf\Internal\Message
{
    protected $request;

    public function __construct() {
        \GPBMetadata\Tracer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.ControlRequest control_request = 1;</code>
     * @return \Com\Thapovan\Orion\Proto\ControlRequest
     */
    public function getControlRequest()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.ControlRequest control_request = 1;</code>
     * @param \Com\Thapovan\Orion\Proto\ControlRequest $var
     * @return $this
     */
    public function setControlRequest($var)
    {
        GPBUtil::checkMessage($var, \Com\Thapovan\Orion\Proto\ControlRequest::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.Span span_data = 2;</code>
     * @return \Com\Thapovan\Orion\Proto\Span
     */
    public function getSpanData()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.com.thapovan.orion.proto.Span span_data = 2;</code>
     * @param \Com\Thapovan\Orion\Proto\Span $var
     * @return $this
     */
    public function setSpanData($var)
    {
        GPBUtil::checkMessage($var, \Com\Thapovan\Orion\Proto\Span::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        return $this->whichOneof("request");
    }

}

