<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Span.proto

namespace GPBMetadata;

class Span
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Trace::initOnce();
        \GPBMetadata\Events::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa3030a0a5370616e2e70726f746f1218636f6d2e746861706f76616e2e" .
            "6f72696f6e2e70726f746f1a0c4576656e74732e70726f746f22e0020a04" .
            "5370616e12360a0d74726163655f636f6e7465787418012001280b321f2e" .
            "636f6d2e746861706f76616e2e6f72696f6e2e70726f746f2e5472616365" .
            "120f0a077370616e5f6964180220012809123b0a0b73746172745f657665" .
            "6e7418032001280b32242e636f6d2e746861706f76616e2e6f72696f6e2e" .
            "70726f746f2e53746172744576656e74480012370a09656e645f6576656e" .
            "7418042001280b32222e636f6d2e746861706f76616e2e6f72696f6e2e70" .
            "726f746f2e456e644576656e74480012370a096c6f675f6576656e741805" .
            "2001280b32222e636f6d2e746861706f76616e2e6f72696f6e2e70726f74" .
            "6f2e4c6f674576656e74480012110a0974696d657374616d701806200128" .
            "0412140a0c736572766963655f6e616d6518072001280912160a0e657665" .
            "6e745f6c6f636174696f6e18082001280912160a0e706172656e745f7370" .
            "616e5f696418092001280942070a056576656e7442025001620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

