<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Trace.proto

namespace GPBMetadata;

class Trace
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4e0a0b54726163652e70726f746f1218636f6d2e746861706f76616e2e" .
            "6f72696f6e2e70726f746f22190a05547261636512100a0874726163655f" .
            "696418012001280942025001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

